#!/bin/bash

alias glo='git lo'
alias gco='git co'
alias gbr='git br'
alias gbrd='git brd'
alias gpl='git pull'
alias gcd='git co develop && gpl && git fch'
alias gcs='git co staging && gpl && git fch'
alias gcm='git co main && gpl && git fch'
alias gcp='git co -'
alias grd='git rb develop'
alias grs='git rb staging'
alias grm='git rb main'
alias grbc='git -c core.editor=true rb --continue'
alias gcpc='git -c core.editor=true cp --continue'
alias gmgc='git -c core.editor=true merge --continue'
alias gp='git push --set-upstream origin $(git symbolic-ref --short HEAD)'
alias gpf='git push --force'
alias ga='git amend'
alias gap='ga && gp'
alias gapf='ga && gpf'
alias grfd='gcd && gcp && grd'
alias grfs='gcs && gcp && grs'
alias grfm='gcm && gcp && grm'